#!/usr/bin/python3

import csv, datetime, getopt, os, sys

def logo():
    print('''
##############################################################
##############################################################
#
# PYTHON 3
# BATCH ORGANIZATIONAL INFORMATION SCRIPT v0.3
#
# Created by: Andrew Sturm
# Created on: 2020-07-27
#
##############################################################
##############################################################

This script will go through the process of filling your Google Directory with your organizational contact information.

The CSV is generated by the command: 'gam print users allfields todrive'.

From there, File > Download > CSV and point this program to that path.
''')
# TODO: This is not the most efficient 'gam print' GAM command. Fix this.

def main(argv):
    # Variables
    choice = ""
    emails = []
    gam = "/root/bin/gam/gam"

    # Check for the correct arguments
    try:
        opts, args = getopt.getopt(argv,"hi:rvwy",["help","input","read","version","write","yes"])
    except getopt.GetoptError:
        print("Invalid argument.\n\nUsage: orginfo.py -i file")
        exit()

    # Get opt cases
    try:
        for opt, arg in opts:
            if opt in ("-h","--help"):
                print("Usage: orginfo.py -i file")
                print("The CSV is generated by the command: 'gam print users allfields todrive'.")
                print("From there, File > Download > CSV and point this program to that path.")
                exit()
            elif opt in ("-i","--input"):
                    try:
                        with open(arg, newline='') as csvfile:
                            reader = csv.DictReader(csvfile)
                            header = reader.fieldnames

                            for row in reader:
# Mandatory Fields
                                building = row['Building']
                                email = row['Email']
                                org = row['Organization']
                                title = row['Title']
                                emails.append(email)
# Conditional Fields
# TODO: Add conditionals for certain conditional/optional cases, which will alter the GAM command at the end.
#                                if "Building" in header:
#                                    building = row['Building']

                    except KeyboardInterrupt:
                        print("Keyboard interrupt signal detected.\nExiting...")
                        exit()
            elif opt in ("-r","--read"):
                read = TRUE
            elif opt in ("-w","--write"):
                write = TRUE
            elif opt in ("-v","--version"):
                logo()
                exit()
            elif opt in ("-y","--yes"):
                choice = 'y'

    except FileNotFoundError:
        print("File not found.")
        print("Usage: orginfo.py -i file")
        exit()

    except KeyError:
        print("Check your CSV file for validity and try again.\nCreate CSV from GAM with: 'gam print users allfields todrive'")
        exit()

    except IsADirectoryError:
        print("Check your -i path. Ensure it is pointing to a .csv and not a directory.")
        exit()

    # Check with user before suspending
    if choice == '':
        print(emails)
        choice = input("The following accounts will have their organizational contact information updated. Do you wish to continue? [y/N]")
        if choice.lower() == "y":
            for row in emails:
# TODO: Figure out the most efficient way to be able to alter the necessary GAM command based on the above conditionals.
                cmd = (gam+" update user "+email+" organization name \""+org+"\" title \""+title+"\" location \""+building+"\" primary phone type work value \""+phone+"\" primary")
#                os.system(cmd)
                print(cmd)
        else:
            exit()

# Start the main loop
if __name__ == "__main__":
    if sys.argv[1:] != []:
        main(sys.argv[1:])
    else:
        print("Usage: orginfo.py -i file")
